[tool.flake8]
exclude = [".git", "venv", ".venv", ".venv13", "__pycache__"]
max-complexity = 10
max-line-length = 100
ignore = ["D203", "D213", "E501", "E203", "E123", "W503"]

[tool.pydocstyle]
match-dir = "(?!tests)(?!resources)(?!docs)[^\\.].*"
convention = "google"
add-ignore = ["D105", "D203", "D213"]

[tool.pep257]
ignore = ["D105", "D107", "D203", "D213", "D301"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
norecursedirs = [".tox", "venv", ".venv", ".git", ".venv13"]
filterwarnings = [
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning",
    "ignore:\"@coroutine\" decorator is deprecated since Python 3.8, use \"async def\" instead:DeprecationWarning"
]

[tool.pylint.master]
ignore = ["venv", ".venv", ".venv13", ".git", "tasks.py"]
